#quarkus.qute.alt-expr-syntax=true
quarkus.http.port=8081
#quarkus.roq.generator.paths=/,/static/**,/about/,/blog/
# Indique à Quarkus de surveiller vos dossiers de contenu Roq pour le Live Reload
quarkus.live-reload.watched-resources=content/*.*,content/**/*.md,content/**/*.html,_posts/**/*.md,posts/**/*.md
